### ISSUE TITLE
Issues with master branch; 400 bad request

### ISSUE THREAD

**Issue by aattias** [indeedsecurity/carbonbeat#8]
Heya - I've configured the yaml with:

carbonbeat:
  period: 1m

  api:
    id: xxxx
    key: xxxxxxxxxxxxxxxxxxx
    host: https://defense-prod0x.conferdeploy.net
  siem:
    id: xxxx
    key: xxxxxxxxxxxxxxxxxxx
    host: https://defense-prod0x.conferdeploy.net

api is an API key and siem is an API key with the type of SIEM in the CB PSC portal.

---

After it polls in 1m, the following is outputted:
`2020/08/26 00:42:46.258507 carbonbeat.go:113: CRIT fetching notifications from the API failed, got: BAD REQUEST: <html>`
`<head><title>400 Bad Request</title></head>`
`<body bgcolor="white">`
`<center><h1>400 Bad Request</h1></center>`
`</body>`
`</html>`
`2020/08/26 00:42:46.258539 carbonbeat.go:79: CRIT Fetching SIEM events failed, got: BAD REQUEST: <html>`
`<head><title>400 Bad Request</title></head>`
`<body bgcolor="white">`
`<center><h1>400 Bad Request</h1></center>`
`</body>`
`</html>`
`2020/08/26 00:42:46.258970 carbonbeat.go:132: CRIT fetching audit events from the API failed, got: BAD REQUEST: <html>`
`<head><title>400 Bad Request</title></head>`
`<body bgcolor="white">`
`<center><h1>400 Bad Request</h1></center>`
`</body>`
`</html>`
`2020/08/26 00:42:46.258995 carbonbeat.go:90: CRIT Fetching API events failed, got: BAD REQUEST: <html>`
`<head><title>400 Bad Request</title></head>`
`<body bgcolor="white">`
`<center><h1>400 Bad Request</h1></center>`
`</body>`
`</html>`

**Comment by aattias** [comment]
I was able to resolve by commenting out the following items in carbonclient/requests.go:

`req.Host = c.cfg.SIEMHost`
and
`req.Host = c.cfg.APIHost`

(fyi, I built with Golang 1.15)

**Comment by dustin-decker** [comment]
This is probably because it expects a hostname, not a URL. But the request also doesn't need to have the host explicitly set, as you found, because it gets parsed from the given URL.
